pipeline {
  agent any
  environment {
    ISO = 'image_2021-10-31-WaziGate.zip'
  }
  stages {
    stage('Prepare') {
      steps {
        copyArtifacts projectName: 'compiling/WaziGate_ISO', selector: specific('47')
        sh 'sudo ./mount_ISO 2021-10-31-WaziGate'
      }
    }
    stage('Run') {
      steps {
        sh 'ssh pi@$WAZIGATE_URL "echo loragateway | sudo shutdown -r now"'
      }
    }
  }
}
