pipeline {
  agent any
  environment {
    ISO = 'image_2021-10-31-WaziGate.zip'
  }
  stages {
    stage('Prepare') {
      steps {
        dir("Staging") {
          copyArtifacts projectName: 'compiling/WaziGate_ISO', selector: specific('50')
          sh 'ls'
          sh 'sudo ./mount_ISO.sh 2021-11-02-WaziGate'
        }
      }
    }
    stage('Run') {
      steps {
        sh "sudo sshpass -p loragateway ssh pi@$WAZIGATE_IP \\'sudo reboot now\\'"
      }
    }
  }
}
