pipeline {
  agent any
  environment {
    ARDUINO_DIRECTORIES_USER = '/home/cdupont/Documents/Waziup/WaziDev/'
  }
  stages {
    stage('Prepare') {
      steps {
        sh 'pip3 install unittest-xml-reporting'
      }
    }
    stage('Flash WaziDev') {
      steps {
        echo "WaziDev port is $WAZIDEV_PORT"
        dir('WaziDev'){
          git url: 'https://github.com/Waziup/WaziDev.git'
          withEnv(["PATH=$PATH:/home/linuxbrew/.linuxbrew/bin/"]) {
            dir("tests/LoRaWAN-test/") {
              sh 'ls'
              sh 'arduino-cli compile -p $WAZIDEV_PORT --fqbn arduino:avr:pro:cpu=8MHzatmega328'
              sh 'sudo -E arduino-cli upload -p $WAZIDEV_PORT --fqbn arduino:avr:pro:cpu=8MHzatmega328'
            }
          }
        }
      }
    }
    stage('Test') {
      steps {
        dir('IntegrationTests'){
          sh 'sudo -E python3 -m unittest -v integration-tests'
        }
      }
    }
  }
  post {
    always {
      junit 'results.xml'
    }
  }
}
