pipeline {
    agent any
    environment {
        ARDUINO_DIRECTORIES_USER = '/home/cdupont/Documents/Waziup/WaziDev/'
        WAZIDEV_PORT = '/dev/ttyUSB0'
    }
    stages {
        stage('Prepare') {
            steps {
                git url: 'https://github.com/Waziup/WaziDev.git'
                withEnv(["PATH=$PATH:/home/linuxbrew/.linuxbrew/bin/"]) {
                  //sh 'brew update'
                  //sh 'brew install arduino-cli'
                  sh 'ls'
                  dir("WaziDev/tests/LoRaWAN-test/") {
                    sh 'ls'
                    sh 'arduino-cli compile -p $WAZIDEV_PORT --fqbn arduino:avr:pro:cpu=8MHzatmega328'
                    sh 'arduino-cli upload -p $WAZIDEV_PORT --fqbn arduino:avr:pro:cpu=8MHzatmega328'
                  }
                }
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
